name: Make Reference Image

on:
  workflow_dispatch: null

permissions:
  contents: write

env:
 BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14]

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
          ref: ${{ github.ref || github.ref_name }}

      # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
      - name: Configure Git for pushing from actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install roman_imsim
        run: |
          python -m pip install --upgrade pip
          if git ls-remote --exit-code https://github.com/DukeCosmology/roman_imsim.git ${BRANCH_NAME}; then
              echo "branch ${BRANCH_NAME} exists in roman_imsim"
              pip install git+https://github.com/DukeCosmology/roman_imsim.git@${BRANCH_NAME}
          else
              echo "branch ${BRANCH_NAME} does not exist in roman_imsim; using default"
              pip install git+https://github.com/DukeCosmology/roman_imsim.git
          fi

      - name: Run GalSim
        run: |
          galsim hack.yaml

      - name: Commit and push output
        run: |
          if fitsdiff --ignore-keywords VERSION output/RomanWAS_new/images/truth/Roman_WAS_truth_J129_12909_4.fits.gz reference/RomanWAS_new/images/truth/Roman_WAS_truth_J129_12909_4.fits.gz; then
              echo "reference image is unchanged"
          else
              echo "reference image is changed"
              mv -v output/RomanWAS_new/images/truth/Roman_WAS_truth_J129_12909_4.fits.gz reference/RomanWAS_new/images/truth/Roman_WAS_truth_J129_12909_4.fits.gz
          fi

          if diff output/RomanWAS_new/truth/Roman_WAS_index_J129_12909_4.txt reference/RomanWAS_new/truth/Roman_WAS_index_J129_12909_4.txt; then
              echo "reference table is unchanged"
          else
              echo "reference table is changed"
              mv -v output/RomanWAS_new/truth/Roman_WAS_index_J129_12909_4.txt reference/RomanWAS_new/truth/Roman_WAS_index_J129_12909_4.txt
          fi

          if git diff --exit-code; then
              echo "reference/ is unchanged; no action needed"
          else
              echo "reference/ is changed; pushing updates"
              git add reference
              git commit -m "Update reference"
              git push
          fi

